# Generated by Django 4.2 on 2023-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=256)),
                ('product_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1)),
                ('product_price', models.CharField(max_length=256)),
                ('product_desc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'my_product',
            },
        ),
    ]
