# Generated by Django 4.2 on 2023-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
