# Generated by Django 4.2 on 2023-04-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_product_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.product')),
                ('inbound_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('erp.product',),
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.product')),
                ('outbound_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('erp.product',),
        ),
    ]
