# Generated by Django 4.2 on 2023-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_inbound_outbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='inbound_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outbound',
            name='outbound_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
